name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: install build tools
      run: sudo apt-get install nasm grub-common

    - name: compile
      run: ./generate_sources.sh && make
